- hosts: 127.0.0.1 # all | testepunk  | "{{ tenant }}"
  connection: local
  #become: yes
  #become_user: root #dica de segurança / not all become / root all?
  # em que python está rodando antes de instalar o boto? importante ver

  tasks:
  # - name: ensure apache is at the latest version
  #   yum:
  #     name: httpd
  #     state: latest
  - ec2:
      key_name: camidevops
      region: us-east-1
      instance_type: t2.micro
      image: ami-026dea5602e368e96
      wait: yes
      count: 1
      group: default
      instance_tags:
        name: teste1
      monitoring: yes
      termination_protection: yes
      assign_public_ip: yes
#      vpc_subnet_id: subnet-0ca60f40
      vpc_subnet_id: 0ca60f40
