- hosts: 127.0.0.1 # all | testepunk  | {{ tenant }}
  connection: local
  become: yes
  become_user: root

  tasks:
  - name: ensure apache is at the latest version
    yum:
      name: httpd
      state: latest

  - name: Creates directory
    file:
      path: /home/ec2-user/teste/
      state: directory
      owner: ec2-user
      group: ec2-user #dica do user criptomaluco

  - name: Copy file with owner and permissions
    copy:
      src: /home/ec2-user/teste.txt
      dest: /home/ec2-user/teste/teste.txt
      owner: ec2-user
      group: ec2-user #dica do user criptomaluco
      mode: '0644'

# - name: Copiando de lá pra cá (fetch)
#   fetch:
#     src: /tmp/somefile #máquina do hosts
#     dest: /tmp/fetched #maquina que ta executando o ansible

  - name: Add a line to ansible hosts
    lineinfile:
      path: /etc/ansible/hosts
      line: "[testecamilla]\n192.168.1.99\tansible_ssh_private_key_file=/home/ec2-user/teste.pem"
      create: yes


# # Basic provisioning example
# - ec2:
#     key_name: mykey
#     instance_type: t2.micro
#     image: ami-123456
#     wait: yes
#     group: webserver
#     count: 3
#     vpc_subnet_id: subnet-29e63245
#     assign_public_ip: yes